version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tjddn062$
      POSTGRES_DB: common
    ports:
      - 5432:5432
